server:
  servlet:
    context-path: /bms
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      filter
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
mybatis:
    type-aliases-package: cn.future.bms.entity
    mapper-locations: classpath:mapper/*.xml
mapper:
    mappers: cn.future.bms.mapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql