server:
  servlet:
    context-path: /bms
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
#  jpa:
#    hibernate:
#      ddl-auto: update
#    open-in-view: true
#    show-sql: true
mybatis:
    type-aliases-package: cn.future.bms.support.entity
    mapper-locations: classpath:mapper/*.xml
mapper:
    mappers:
        - cn.future.bms.support.mapper.BaseMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    192.168.200.128:22122
